
package com.coopdb.data;

import java.math.BigDecimal;
import java.util.Date;


/**
 *  COOPDB.Tbcifemployment
 *  02/23/2023 13:04:33
 * 
 */
public class Tbcifemployment {

    private Integer employmentid;
    private String emprecordtype;
    private String employername;
    private String position;
    private String empstatus;
    private String cifno;
    private String employertin;
    private String employerphoneno;
    private String psic;
    private String psoc;
    private String seafarerid;
    private String seafarervessel;
    private String seafarerduration;
    private Date seafarerembarkationdate;
    private Date seafarerdisembarkationdate;
    private BigDecimal seafarerpercentageofallotment;
    private String seafarerallottee1;
    private String seafarerallottee2;
    private String department;
    private String rank;
    private Date datehiredfrom;
    private Date datehiredto;
    private Integer yearsofservice;
    private String immediatehead;
    private Integer grossincome;
    private String annualmonthind;
    private String currency;
    private String fulladdress1;
    private String streetno1;
    private String subdivision1;
    private String country;
    private String province1;
    private String city1;
    private String barangay1;
    private String postalcode1;
    private String postalcodename1;
    private String divisioncode;
    private String stationcode;
    private String employeeno;
    private String regioncode;
    private String countrycodephone;
    private String areacodephone;
    private String empcifno;
    private String otheremploymentstatus;
    private String psiccode;
    private String psiclevel1;
    private String psiclevel2;
    private String psiclevel3;
    private String psiclevel4;
    private String psoccode;
    private String psoclevel1;
    private String psoclevel2;
    private String psoclevel3;
    private String psoclevel4;
    private Boolean isdepedemployee;
    private Integer monthsofservice;
    private String positioncategory;
    private String otherpositioncategory;
    private Boolean ispresent;
    private String occupationstatus;
    private String mngempid;
    private Boolean isautogenerated;
    private String depedposition;
    private String businesstype;
    private String employeraddress;

    public Integer getEmploymentid() {
        return employmentid;
    }

    public void setEmploymentid(Integer employmentid) {
        this.employmentid = employmentid;
    }

    public String getEmprecordtype() {
        return emprecordtype;
    }

    public void setEmprecordtype(String emprecordtype) {
        this.emprecordtype = emprecordtype;
    }

    public String getEmployername() {
        return employername;
    }

    public void setEmployername(String employername) {
        this.employername = employername;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getEmpstatus() {
        return empstatus;
    }

    public void setEmpstatus(String empstatus) {
        this.empstatus = empstatus;
    }

    public String getCifno() {
        return cifno;
    }

    public void setCifno(String cifno) {
        this.cifno = cifno;
    }

    public String getEmployertin() {
        return employertin;
    }

    public void setEmployertin(String employertin) {
        this.employertin = employertin;
    }

    public String getEmployerphoneno() {
        return employerphoneno;
    }

    public void setEmployerphoneno(String employerphoneno) {
        this.employerphoneno = employerphoneno;
    }

    public String getPsic() {
        return psic;
    }

    public void setPsic(String psic) {
        this.psic = psic;
    }

    public String getPsoc() {
        return psoc;
    }

    public void setPsoc(String psoc) {
        this.psoc = psoc;
    }

    public String getSeafarerid() {
        return seafarerid;
    }

    public void setSeafarerid(String seafarerid) {
        this.seafarerid = seafarerid;
    }

    public String getSeafarervessel() {
        return seafarervessel;
    }

    public void setSeafarervessel(String seafarervessel) {
        this.seafarervessel = seafarervessel;
    }

    public String getSeafarerduration() {
        return seafarerduration;
    }

    public void setSeafarerduration(String seafarerduration) {
        this.seafarerduration = seafarerduration;
    }

    public Date getSeafarerembarkationdate() {
        return seafarerembarkationdate;
    }

    public void setSeafarerembarkationdate(Date seafarerembarkationdate) {
        this.seafarerembarkationdate = seafarerembarkationdate;
    }

    public Date getSeafarerdisembarkationdate() {
        return seafarerdisembarkationdate;
    }

    public void setSeafarerdisembarkationdate(Date seafarerdisembarkationdate) {
        this.seafarerdisembarkationdate = seafarerdisembarkationdate;
    }

    public BigDecimal getSeafarerpercentageofallotment() {
        return seafarerpercentageofallotment;
    }

    public void setSeafarerpercentageofallotment(BigDecimal seafarerpercentageofallotment) {
        this.seafarerpercentageofallotment = seafarerpercentageofallotment;
    }

    public String getSeafarerallottee1() {
        return seafarerallottee1;
    }

    public void setSeafarerallottee1(String seafarerallottee1) {
        this.seafarerallottee1 = seafarerallottee1;
    }

    public String getSeafarerallottee2() {
        return seafarerallottee2;
    }

    public void setSeafarerallottee2(String seafarerallottee2) {
        this.seafarerallottee2 = seafarerallottee2;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getRank() {
        return rank;
    }

    public void setRank(String rank) {
        this.rank = rank;
    }

    public Date getDatehiredfrom() {
        return datehiredfrom;
    }

    public void setDatehiredfrom(Date datehiredfrom) {
        this.datehiredfrom = datehiredfrom;
    }

    public Date getDatehiredto() {
        return datehiredto;
    }

    public void setDatehiredto(Date datehiredto) {
        this.datehiredto = datehiredto;
    }

    public Integer getYearsofservice() {
        return yearsofservice;
    }

    public void setYearsofservice(Integer yearsofservice) {
        this.yearsofservice = yearsofservice;
    }

    public String getImmediatehead() {
        return immediatehead;
    }

    public void setImmediatehead(String immediatehead) {
        this.immediatehead = immediatehead;
    }

    public Integer getGrossincome() {
        return grossincome;
    }

    public void setGrossincome(Integer grossincome) {
        this.grossincome = grossincome;
    }

    public String getAnnualmonthind() {
        return annualmonthind;
    }

    public void setAnnualmonthind(String annualmonthind) {
        this.annualmonthind = annualmonthind;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getFulladdress1() {
        return fulladdress1;
    }

    public void setFulladdress1(String fulladdress1) {
        this.fulladdress1 = fulladdress1;
    }

    public String getStreetno1() {
        return streetno1;
    }

    public void setStreetno1(String streetno1) {
        this.streetno1 = streetno1;
    }

    public String getSubdivision1() {
        return subdivision1;
    }

    public void setSubdivision1(String subdivision1) {
        this.subdivision1 = subdivision1;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getProvince1() {
        return province1;
    }

    public void setProvince1(String province1) {
        this.province1 = province1;
    }

    public String getCity1() {
        return city1;
    }

    public void setCity1(String city1) {
        this.city1 = city1;
    }

    public String getBarangay1() {
        return barangay1;
    }

    public void setBarangay1(String barangay1) {
        this.barangay1 = barangay1;
    }

    public String getPostalcode1() {
        return postalcode1;
    }

    public void setPostalcode1(String postalcode1) {
        this.postalcode1 = postalcode1;
    }

    public String getPostalcodename1() {
        return postalcodename1;
    }

    public void setPostalcodename1(String postalcodename1) {
        this.postalcodename1 = postalcodename1;
    }

    public String getDivisioncode() {
        return divisioncode;
    }

    public void setDivisioncode(String divisioncode) {
        this.divisioncode = divisioncode;
    }

    public String getStationcode() {
        return stationcode;
    }

    public void setStationcode(String stationcode) {
        this.stationcode = stationcode;
    }

    public String getEmployeeno() {
        return employeeno;
    }

    public void setEmployeeno(String employeeno) {
        this.employeeno = employeeno;
    }

    public String getRegioncode() {
        return regioncode;
    }

    public void setRegioncode(String regioncode) {
        this.regioncode = regioncode;
    }

    public String getCountrycodephone() {
        return countrycodephone;
    }

    public void setCountrycodephone(String countrycodephone) {
        this.countrycodephone = countrycodephone;
    }

    public String getAreacodephone() {
        return areacodephone;
    }

    public void setAreacodephone(String areacodephone) {
        this.areacodephone = areacodephone;
    }

    public String getEmpcifno() {
        return empcifno;
    }

    public void setEmpcifno(String empcifno) {
        this.empcifno = empcifno;
    }

    public String getOtheremploymentstatus() {
        return otheremploymentstatus;
    }

    public void setOtheremploymentstatus(String otheremploymentstatus) {
        this.otheremploymentstatus = otheremploymentstatus;
    }

    public String getPsiccode() {
        return psiccode;
    }

    public void setPsiccode(String psiccode) {
        this.psiccode = psiccode;
    }

    public String getPsiclevel1() {
        return psiclevel1;
    }

    public void setPsiclevel1(String psiclevel1) {
        this.psiclevel1 = psiclevel1;
    }

    public String getPsiclevel2() {
        return psiclevel2;
    }

    public void setPsiclevel2(String psiclevel2) {
        this.psiclevel2 = psiclevel2;
    }

    public String getPsiclevel3() {
        return psiclevel3;
    }

    public void setPsiclevel3(String psiclevel3) {
        this.psiclevel3 = psiclevel3;
    }

    public String getPsiclevel4() {
        return psiclevel4;
    }

    public void setPsiclevel4(String psiclevel4) {
        this.psiclevel4 = psiclevel4;
    }

    public String getPsoccode() {
        return psoccode;
    }

    public void setPsoccode(String psoccode) {
        this.psoccode = psoccode;
    }

    public String getPsoclevel1() {
        return psoclevel1;
    }

    public void setPsoclevel1(String psoclevel1) {
        this.psoclevel1 = psoclevel1;
    }

    public String getPsoclevel2() {
        return psoclevel2;
    }

    public void setPsoclevel2(String psoclevel2) {
        this.psoclevel2 = psoclevel2;
    }

    public String getPsoclevel3() {
        return psoclevel3;
    }

    public void setPsoclevel3(String psoclevel3) {
        this.psoclevel3 = psoclevel3;
    }

    public String getPsoclevel4() {
        return psoclevel4;
    }

    public void setPsoclevel4(String psoclevel4) {
        this.psoclevel4 = psoclevel4;
    }

    public Boolean getIsdepedemployee() {
        return isdepedemployee;
    }

    public void setIsdepedemployee(Boolean isdepedemployee) {
        this.isdepedemployee = isdepedemployee;
    }

    public Integer getMonthsofservice() {
        return monthsofservice;
    }

    public void setMonthsofservice(Integer monthsofservice) {
        this.monthsofservice = monthsofservice;
    }

    public String getPositioncategory() {
        return positioncategory;
    }

    public void setPositioncategory(String positioncategory) {
        this.positioncategory = positioncategory;
    }

    public String getOtherpositioncategory() {
        return otherpositioncategory;
    }

    public void setOtherpositioncategory(String otherpositioncategory) {
        this.otherpositioncategory = otherpositioncategory;
    }

    public Boolean getIspresent() {
        return ispresent;
    }

    public void setIspresent(Boolean ispresent) {
        this.ispresent = ispresent;
    }

    public String getOccupationstatus() {
        return occupationstatus;
    }

    public void setOccupationstatus(String occupationstatus) {
        this.occupationstatus = occupationstatus;
    }

    public String getMngempid() {
        return mngempid;
    }

    public void setMngempid(String mngempid) {
        this.mngempid = mngempid;
    }

    public Boolean getIsautogenerated() {
        return isautogenerated;
    }

    public void setIsautogenerated(Boolean isautogenerated) {
        this.isautogenerated = isautogenerated;
    }

    public String getDepedposition() {
        return depedposition;
    }

    public void setDepedposition(String depedposition) {
        this.depedposition = depedposition;
    }

    public String getBusinesstype() {
        return businesstype;
    }

    public void setBusinesstype(String businesstype) {
        this.businesstype = businesstype;
    }

    public String getEmployeraddress() {
        return employeraddress;
    }

    public void setEmployeraddress(String employeraddress) {
        this.employeraddress = employeraddress;
    }

}
