
package com.coopdb.data;

import java.math.BigDecimal;
import java.util.Date;


/**
 *  COOPDB.Tblosbusiness
 *  11/03/2020 13:58:29
 * 
 */
public class Tblosbusiness {

    private Integer businessid;
    private String businessname;
    private String businesstype;
    private String natureofbusiness;
    private String cifno;
    private String businesstin;
    private String businessclass;
    private String businessphoneno;
    private String businessfaxno;
    private String emailaddress;
    private String psic;
    private Date incoporationdate;
    private Integer yearsofservice;
    private BigDecimal grossincome;
    private String annualmonthind;
    private String currency;
    private String fulladdress1;
    private String streetno1;
    private String subdivision1;
    private String country1;
    private String province1;
    private String city1;
    private String barangay1;
    private String postalcode1;
    private String postalcodename;
    private String homeownership1;
    private String otherhomeownership1;
    private Date occupiedsince1;
    private String countrycodephone;
    private String areacodephone;
    private String countrycodefax;
    private String areacodefax;
    private String buscifno;
    private String psiccode;
    private String psiclevel1;
    private String psiclevel2;
    private String psiclevel3;
    private String psiclevel4;
    private String mngbusid;
    private Boolean isautogenerated;
    private String genmanager;
    private String gmcif;

    public Integer getBusinessid() {
        return businessid;
    }

    public void setBusinessid(Integer businessid) {
        this.businessid = businessid;
    }

    public String getBusinessname() {
        return businessname;
    }

    public void setBusinessname(String businessname) {
        this.businessname = businessname;
    }

    public String getBusinesstype() {
        return businesstype;
    }

    public void setBusinesstype(String businesstype) {
        this.businesstype = businesstype;
    }

    public String getNatureofbusiness() {
        return natureofbusiness;
    }

    public void setNatureofbusiness(String natureofbusiness) {
        this.natureofbusiness = natureofbusiness;
    }

    public String getCifno() {
        return cifno;
    }

    public void setCifno(String cifno) {
        this.cifno = cifno;
    }

    public String getBusinesstin() {
        return businesstin;
    }

    public void setBusinesstin(String businesstin) {
        this.businesstin = businesstin;
    }

    public String getBusinessclass() {
        return businessclass;
    }

    public void setBusinessclass(String businessclass) {
        this.businessclass = businessclass;
    }

    public String getBusinessphoneno() {
        return businessphoneno;
    }

    public void setBusinessphoneno(String businessphoneno) {
        this.businessphoneno = businessphoneno;
    }

    public String getBusinessfaxno() {
        return businessfaxno;
    }

    public void setBusinessfaxno(String businessfaxno) {
        this.businessfaxno = businessfaxno;
    }

    public String getEmailaddress() {
        return emailaddress;
    }

    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress;
    }

    public String getPsic() {
        return psic;
    }

    public void setPsic(String psic) {
        this.psic = psic;
    }

    public Date getIncoporationdate() {
        return incoporationdate;
    }

    public void setIncoporationdate(Date incoporationdate) {
        this.incoporationdate = incoporationdate;
    }

    public Integer getYearsofservice() {
        return yearsofservice;
    }

    public void setYearsofservice(Integer yearsofservice) {
        this.yearsofservice = yearsofservice;
    }

    public BigDecimal getGrossincome() {
        return grossincome;
    }

    public void setGrossincome(BigDecimal grossincome) {
        this.grossincome = grossincome;
    }

    public String getAnnualmonthind() {
        return annualmonthind;
    }

    public void setAnnualmonthind(String annualmonthind) {
        this.annualmonthind = annualmonthind;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getFulladdress1() {
        return fulladdress1;
    }

    public void setFulladdress1(String fulladdress1) {
        this.fulladdress1 = fulladdress1;
    }

    public String getStreetno1() {
        return streetno1;
    }

    public void setStreetno1(String streetno1) {
        this.streetno1 = streetno1;
    }

    public String getSubdivision1() {
        return subdivision1;
    }

    public void setSubdivision1(String subdivision1) {
        this.subdivision1 = subdivision1;
    }

    public String getCountry1() {
        return country1;
    }

    public void setCountry1(String country1) {
        this.country1 = country1;
    }

    public String getProvince1() {
        return province1;
    }

    public void setProvince1(String province1) {
        this.province1 = province1;
    }

    public String getCity1() {
        return city1;
    }

    public void setCity1(String city1) {
        this.city1 = city1;
    }

    public String getBarangay1() {
        return barangay1;
    }

    public void setBarangay1(String barangay1) {
        this.barangay1 = barangay1;
    }

    public String getPostalcode1() {
        return postalcode1;
    }

    public void setPostalcode1(String postalcode1) {
        this.postalcode1 = postalcode1;
    }

    public String getPostalcodename() {
        return postalcodename;
    }

    public void setPostalcodename(String postalcodename) {
        this.postalcodename = postalcodename;
    }

    public String getHomeownership1() {
        return homeownership1;
    }

    public void setHomeownership1(String homeownership1) {
        this.homeownership1 = homeownership1;
    }

    public String getOtherhomeownership1() {
        return otherhomeownership1;
    }

    public void setOtherhomeownership1(String otherhomeownership1) {
        this.otherhomeownership1 = otherhomeownership1;
    }

    public Date getOccupiedsince1() {
        return occupiedsince1;
    }

    public void setOccupiedsince1(Date occupiedsince1) {
        this.occupiedsince1 = occupiedsince1;
    }

    public String getCountrycodephone() {
        return countrycodephone;
    }

    public void setCountrycodephone(String countrycodephone) {
        this.countrycodephone = countrycodephone;
    }

    public String getAreacodephone() {
        return areacodephone;
    }

    public void setAreacodephone(String areacodephone) {
        this.areacodephone = areacodephone;
    }

    public String getCountrycodefax() {
        return countrycodefax;
    }

    public void setCountrycodefax(String countrycodefax) {
        this.countrycodefax = countrycodefax;
    }

    public String getAreacodefax() {
        return areacodefax;
    }

    public void setAreacodefax(String areacodefax) {
        this.areacodefax = areacodefax;
    }

    public String getBuscifno() {
        return buscifno;
    }

    public void setBuscifno(String buscifno) {
        this.buscifno = buscifno;
    }

    public String getPsiccode() {
        return psiccode;
    }

    public void setPsiccode(String psiccode) {
        this.psiccode = psiccode;
    }

    public String getPsiclevel1() {
        return psiclevel1;
    }

    public void setPsiclevel1(String psiclevel1) {
        this.psiclevel1 = psiclevel1;
    }

    public String getPsiclevel2() {
        return psiclevel2;
    }

    public void setPsiclevel2(String psiclevel2) {
        this.psiclevel2 = psiclevel2;
    }

    public String getPsiclevel3() {
        return psiclevel3;
    }

    public void setPsiclevel3(String psiclevel3) {
        this.psiclevel3 = psiclevel3;
    }

    public String getPsiclevel4() {
        return psiclevel4;
    }

    public void setPsiclevel4(String psiclevel4) {
        this.psiclevel4 = psiclevel4;
    }

    public String getMngbusid() {
        return mngbusid;
    }

    public void setMngbusid(String mngbusid) {
        this.mngbusid = mngbusid;
    }

    public Boolean getIsautogenerated() {
        return isautogenerated;
    }

    public void setIsautogenerated(Boolean isautogenerated) {
        this.isautogenerated = isautogenerated;
    }

    public String getGenmanager() {
        return genmanager;
    }

    public void setGenmanager(String genmanager) {
        this.genmanager = genmanager;
    }

    public String getGmcif() {
        return gmcif;
    }

    public void setGmcif(String gmcif) {
        this.gmcif = gmcif;
    }

}
