
package com.coopdb.data;

import java.math.BigDecimal;
import java.util.Date;


/**
 *  COOPDB.Tbmanagementlos
 *  08/04/2024 12:54:43
 * 
 */
public class Tbmanagementlos {

    private Integer id;
    private String cifno;
    private String firstname;
    private String middlename;
    private String lastname;
    private String suffix;
    private Date dateofbirth;
    private String position;
    private String nationality;
    private String noofshares;
    private BigDecimal amtsubscribed;
    private BigDecimal ownershippercentage;
    private String relationshipcode;
    private String relatedcifno;
    private String businesstype;
    private String boarddesignation;
    private String signatorylevel;
    private String corporatename;
    private Date dateofincorporation;
    private String customertype;
    private String mngempid;
    private Boolean isautogenerated;
    private String positioncategory;
    private Date datecreated;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCifno() {
        return cifno;
    }

    public void setCifno(String cifno) {
        this.cifno = cifno;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getMiddlename() {
        return middlename;
    }

    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getSuffix() {
        return suffix;
    }

    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    public Date getDateofbirth() {
        return dateofbirth;
    }

    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getNationality() {
        return nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getNoofshares() {
        return noofshares;
    }

    public void setNoofshares(String noofshares) {
        this.noofshares = noofshares;
    }

    public BigDecimal getAmtsubscribed() {
        return amtsubscribed;
    }

    public void setAmtsubscribed(BigDecimal amtsubscribed) {
        this.amtsubscribed = amtsubscribed;
    }

    public BigDecimal getOwnershippercentage() {
        return ownershippercentage;
    }

    public void setOwnershippercentage(BigDecimal ownershippercentage) {
        this.ownershippercentage = ownershippercentage;
    }

    public String getRelationshipcode() {
        return relationshipcode;
    }

    public void setRelationshipcode(String relationshipcode) {
        this.relationshipcode = relationshipcode;
    }

    public String getRelatedcifno() {
        return relatedcifno;
    }

    public void setRelatedcifno(String relatedcifno) {
        this.relatedcifno = relatedcifno;
    }

    public String getBusinesstype() {
        return businesstype;
    }

    public void setBusinesstype(String businesstype) {
        this.businesstype = businesstype;
    }

    public String getBoarddesignation() {
        return boarddesignation;
    }

    public void setBoarddesignation(String boarddesignation) {
        this.boarddesignation = boarddesignation;
    }

    public String getSignatorylevel() {
        return signatorylevel;
    }

    public void setSignatorylevel(String signatorylevel) {
        this.signatorylevel = signatorylevel;
    }

    public String getCorporatename() {
        return corporatename;
    }

    public void setCorporatename(String corporatename) {
        this.corporatename = corporatename;
    }

    public Date getDateofincorporation() {
        return dateofincorporation;
    }

    public void setDateofincorporation(Date dateofincorporation) {
        this.dateofincorporation = dateofincorporation;
    }

    public String getCustomertype() {
        return customertype;
    }

    public void setCustomertype(String customertype) {
        this.customertype = customertype;
    }

    public String getMngempid() {
        return mngempid;
    }

    public void setMngempid(String mngempid) {
        this.mngempid = mngempid;
    }

    public Boolean getIsautogenerated() {
        return isautogenerated;
    }

    public void setIsautogenerated(Boolean isautogenerated) {
        this.isautogenerated = isautogenerated;
    }

    public String getPositioncategory() {
        return positioncategory;
    }

    public void setPositioncategory(String positioncategory) {
        this.positioncategory = positioncategory;
    }

    public Date getDatecreated() {
        return datecreated;
    }

    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }

}
