
package com.coopdb.data;

import java.util.Date;


/**
 *  COOPDB.Tbmemberrelationship
 *  08/27/2024 14:22:56
 * 
 */
public class Tbmemberrelationship {

    private Integer relid;
    private String applicantid;
    private String mainmemberid;
    private String mainmembername;
    private String relatedmemberid;
    private String relationshipcode;
    private String lastname;
    private String firstname;
    private String middlename;
    private String suffix;
    private Date dateofbirth;
    private Boolean issameasapplicantaddress;
    private String streetnoname;
    private String subdivision;
    private String barangay;
    private String stateprovince;
    private String city;
    private String region;
    private String country;
    private String postalcode;
    private Date dateadded;
    private String addedby;
    private Date dateupdated;
    private String updatedby;
    private Boolean isautogenerated;
    private String relationshipdesc;
    private String degreecode;
    private String contactno;
    private String gender;
    private Integer age;
    private Boolean isdependent;
    private Boolean isbeneficiary;
    private Boolean alreadymember;
    private String relatedappid;

    public Integer getRelid() {
        return relid;
    }

    public void setRelid(Integer relid) {
        this.relid = relid;
    }

    public String getApplicantid() {
        return applicantid;
    }

    public void setApplicantid(String applicantid) {
        this.applicantid = applicantid;
    }

    public String getMainmemberid() {
        return mainmemberid;
    }

    public void setMainmemberid(String mainmemberid) {
        this.mainmemberid = mainmemberid;
    }

    public String getMainmembername() {
        return mainmembername;
    }

    public void setMainmembername(String mainmembername) {
        this.mainmembername = mainmembername;
    }

    public String getRelatedmemberid() {
        return relatedmemberid;
    }

    public void setRelatedmemberid(String relatedmemberid) {
        this.relatedmemberid = relatedmemberid;
    }

    public String getRelationshipcode() {
        return relationshipcode;
    }

    public void setRelationshipcode(String relationshipcode) {
        this.relationshipcode = relationshipcode;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getMiddlename() {
        return middlename;
    }

    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }

    public String getSuffix() {
        return suffix;
    }

    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    public Date getDateofbirth() {
        return dateofbirth;
    }

    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }

    public Boolean getIssameasapplicantaddress() {
        return issameasapplicantaddress;
    }

    public void setIssameasapplicantaddress(Boolean issameasapplicantaddress) {
        this.issameasapplicantaddress = issameasapplicantaddress;
    }

    public String getStreetnoname() {
        return streetnoname;
    }

    public void setStreetnoname(String streetnoname) {
        this.streetnoname = streetnoname;
    }

    public String getSubdivision() {
        return subdivision;
    }

    public void setSubdivision(String subdivision) {
        this.subdivision = subdivision;
    }

    public String getBarangay() {
        return barangay;
    }

    public void setBarangay(String barangay) {
        this.barangay = barangay;
    }

    public String getStateprovince() {
        return stateprovince;
    }

    public void setStateprovince(String stateprovince) {
        this.stateprovince = stateprovince;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getPostalcode() {
        return postalcode;
    }

    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    public Date getDateadded() {
        return dateadded;
    }

    public void setDateadded(Date dateadded) {
        this.dateadded = dateadded;
    }

    public String getAddedby() {
        return addedby;
    }

    public void setAddedby(String addedby) {
        this.addedby = addedby;
    }

    public Date getDateupdated() {
        return dateupdated;
    }

    public void setDateupdated(Date dateupdated) {
        this.dateupdated = dateupdated;
    }

    public String getUpdatedby() {
        return updatedby;
    }

    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    public Boolean getIsautogenerated() {
        return isautogenerated;
    }

    public void setIsautogenerated(Boolean isautogenerated) {
        this.isautogenerated = isautogenerated;
    }

    public String getRelationshipdesc() {
        return relationshipdesc;
    }

    public void setRelationshipdesc(String relationshipdesc) {
        this.relationshipdesc = relationshipdesc;
    }

    public String getDegreecode() {
        return degreecode;
    }

    public void setDegreecode(String degreecode) {
        this.degreecode = degreecode;
    }

    public String getContactno() {
        return contactno;
    }

    public void setContactno(String contactno) {
        this.contactno = contactno;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Boolean getIsdependent() {
        return isdependent;
    }

    public void setIsdependent(Boolean isdependent) {
        this.isdependent = isdependent;
    }

    public Boolean getIsbeneficiary() {
        return isbeneficiary;
    }

    public void setIsbeneficiary(Boolean isbeneficiary) {
        this.isbeneficiary = isbeneficiary;
    }

    public Boolean getAlreadymember() {
        return alreadymember;
    }

    public void setAlreadymember(Boolean alreadymember) {
        this.alreadymember = alreadymember;
    }

    public String getRelatedappid() {
        return relatedappid;
    }

    public void setRelatedappid(String relatedappid) {
        this.relatedappid = relatedappid;
    }

}
