package com.etel.relationship;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

import com.cifsdb.data.Tbcifmain;
import com.cifsdb.data.Tbcodetable;
import com.cifsdb.data.Tbcustomerrelationship;
import com.cifsdb.data.Tbtradereference;
import com.coopdb.data.Tbcustomerrelationshiplos;
import com.coopdb.data.Tblosmain;
import com.coopdb.data.Tbtradereferencelos;
import com.etel.codetable.forms.CodetableForm;
import com.etel.common.service.DBService;
import com.etel.common.service.DBServiceImpl;
import com.etel.common.service.DBServiceImplCIF;
import com.etel.forms.FormValidation;
import com.etel.relationship.forms.Relationshipform;
import com.etel.utils.HQLUtil;
import com.etel.utils.UserUtil;

public class RelationshipServiceImpl implements RelationshipService {
//	
//	@SuppressWarnings({ "unchecked" })
//	@Override
//	public String saveRelationship(String cifno) {
//		String flag = "failed";
//		DBService dbService = new DBServiceImplCIF();
//		Map<String, Object> params = HQLUtil.getMap();
//		try {
//			if (cifno != null) {
//				params.put("cifno", cifno);
//				Tbcifmain main = (Tbcifmain) dbService.executeUniqueHQLQuery("FROM Tbcifmain WHERE cifno =:cifno", params);
//				if (main != null){
//					if (main.getCustomertype().equals("1")) {
//						//Individual
//						Tbcifindividual i = (Tbcifindividual) dbService.executeUniqueHQLQuery("FROM Tbcifindividual WHERE cifno=:cifno", params);
//						if (i != null) {
//							
//							/**----------SPOUSE---------*/
//							if (i.getCivilstatus() != null && (i.getCivilstatus().equals("2") || i.getCivilstatus().equals("4"))) {
//								if(i.getSpousecifno()!= null){
//									if ((i.getSpouselastname() != null && i.getSpouselastname() != "")
//											|| (i.getSpousefirstname() != null && i.getSpousefirstname() != "")) {
//										Tbcustomerrelationship spsMain = getCustRelationByRelCode(cifno,"SPS");
//										if(spsMain == null){
//											Tbcustomerrelationship r = new Tbcustomerrelationship();
//											String mname = i.getSpousemiddlename() == null ? "" :i.getSpousemiddlename() == "" ? "" : " "+ i.getSpousemiddlename();
//											String suffix = i.getSpousesuffix() == null ? "" : i.getSpousesuffix() == "" ? "" : " " + i.getSpousesuffix();
//											String spsLastname = i.getSpouselastname() == null ? "" :i.getSpouselastname() == "" ? "" : " "+ i.getSpouselastname();
//											String spsFirstname = i.getSpousefirstname() == null ? "" :i.getSpousefirstname() == "" ? "" : " "+ i.getSpousefirstname();
//											String spsname = spsLastname + ", " + spsFirstname + suffix + mname;
//											r.setAddedby(UserUtil.securityService.getUserName());
//											r.setDateadded(new Date());
//											r.setMaincifname(main.getFullname());
//											r.setMaincifno(main.getCifno());
//											r.setRelatedcifname(spsname);
//											r.setRelatedcifno(i.getSpousecifno());
//											r.setRelationshipcode("SPS");
//											params.put("relCode", r.getRelationshipcode());
//											Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//											if(rel != null){
//												r.setRelationshipdesc(rel.getDesc1());
//											}
//											r.setIsautogenerated(true);
//											if(dbService.save(r)){
//												r.setAddedby(UserUtil.securityService.getUserName());
//												r.setDateadded(new Date());
//												r.setMaincifname(spsname);
//												r.setMaincifno(i.getSpousecifno());
//												r.setRelatedcifname(main.getFullname());
//												r.setRelatedcifno(main.getCifno());
//												r.setRelationshipcode("SPS");
//												params.put("relCode", r.getRelationshipcode());
//												rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//												if(rel != null){
//													r.setRelationshipdesc(rel.getDesc1());
//												}
//												r.setIsautogenerated(true);
//												dbService.save(r);
//											}
//										}else{
//											String mname = i.getSpousemiddlename() == null ? "" :i.getSpousemiddlename() == "" ? "" : " "+ i.getSpousemiddlename();
//											String suffix = i.getSpousesuffix() == null ? "" : i.getSpousesuffix() == "" ? "" : " " + i.getSpousesuffix();
//											String spsLastname = i.getSpouselastname() == null ? "" :i.getSpouselastname() == "" ? "" : " "+ i.getSpouselastname();
//											String spsFirstname = i.getSpousefirstname() == null ? "" :i.getSpousefirstname() == "" ? "" : " "+ i.getSpousefirstname();
//											String spsname = spsLastname + ", " + spsFirstname + suffix + mname;
//											spsMain.setUpdatedby(UserUtil.securityService.getUserName());
//											spsMain.setDateupdated(new Date());
//											spsMain.setMaincifname(main.getFullname());
//											spsMain.setMaincifno(main.getCifno());
//											spsMain.setRelatedcifname(spsname);
//											spsMain.setRelatedcifno(i.getSpousecifno());
//											spsMain.setRelationshipcode("SPS");
//											params.put("relCode", spsMain.getRelationshipcode());
//											Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//											if(rel != null){
//												spsMain.setRelationshipdesc(rel.getDesc1());
//											}
//											spsMain.setIsautogenerated(true);
//											if(dbService.saveOrUpdate(spsMain)){
//												Tbcustomerrelationship spsRel = getCustRelationByRelCode(spsMain.getRelatedcifno(),"SPS");
//												if(spsRel != null){
//													spsRel.setUpdatedby(UserUtil.securityService.getUserName());
//													spsRel.setDateupdated(new Date());
//													spsRel.setMaincifname(spsname);
//													spsRel.setMaincifno(i.getSpousecifno());
//													spsRel.setRelatedcifname(main.getFullname());
//													spsRel.setRelatedcifno(main.getCifno());
//													spsRel.setRelationshipcode("SPS");
//													params.put("relCode", spsRel.getRelationshipcode());
//													rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//													if(rel != null){
//														spsRel.setRelationshipdesc(rel.getDesc1());
//													}
//													spsRel.setIsautogenerated(true);
//													dbService.saveOrUpdate(spsRel);
//												}
//											}
//										}
//									}
//								}else{
//									Tbcustomerrelationship delSpsMain = getCustRelationByRelCode(cifno, "SPS");
//									if(delSpsMain != null ){
//										dbService.delete(delSpsMain);
//										Tbcustomerrelationship delSpsRel = getCustRelationByRelCode(delSpsMain.getRelatedcifno(), "SPS");
//										if(delSpsRel != null){
//											dbService.delete(delSpsRel);
//										}
//									}
//								}
//							}else{
//								Tbcustomerrelationship delSpsMain = getCustRelationByRelCode(cifno, "SPS");
//								if(delSpsMain != null ){
//									dbService.delete(delSpsMain);
//									Tbcustomerrelationship delSpsRel = getCustRelationByRelCode(delSpsMain.getRelatedcifno(), "SPS");
//									if(delSpsRel != null){
//										dbService.delete(delSpsRel);
//									}
//								}
//							}
//							
//							
//							/**----------PARENTS---------*/
//							List<Tbcustomerrelationship> parent = getListOfCustRelationByRelCode(cifno, "PAR");
//							if(parent == null || parent.isEmpty()){
//								//MOTHER
//								if(i.getMothercifno() != null){
//									if(i.getMotherlastname()!=null && i.getMotherfirstname() !=null){
//										Tbcustomerrelationship m = new Tbcustomerrelationship();
//										String mmname = i.getMothermiddlename() == null ? "" :i.getMothermiddlename() == "" ? "" : " "+ i.getMothermiddlename();
//										String msuffix = i.getMothersuffix() == null ? "" : i.getMothersuffix() == "" ? "" : " " + i.getMothersuffix();
//										String mothername = i.getMotherlastname() + ", " + i.getMotherfirstname()+ msuffix + mmname;
//										m.setAddedby(UserUtil.securityService.getUserName());
//										m.setDateadded(new Date());
//										m.setMaincifname(main.getFullname());
//										m.setMaincifno(main.getCifno());
//										m.setRelatedcifname(mothername);
//										m.setRelatedcifno(i.getMothercifno());
//										m.setRelationshipcode("PAR");
//										params.put("relCode", m.getRelationshipcode());
//										Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//										if(rel != null){
//											m.setRelationshipdesc(rel.getDesc1());
//										}
//										m.setIsautogenerated(true);
//										if(dbService.save(m)){
//											m.setAddedby(UserUtil.securityService.getUserName());
//											m.setDateadded(new Date());
//											m.setMaincifname(mothername);
//											m.setMaincifno(i.getMothercifno());
//											m.setRelatedcifname(main.getFullname());
//											m.setRelatedcifno(main.getCifno());
//											m.setRelationshipcode("CHI");
//											params.put("relCode", m.getRelationshipcode());
//											rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//											if(rel != null){
//												m.setRelationshipdesc(rel.getDesc1());
//											}
//											m.setIsautogenerated(true);
//											dbService.save(m);
//										}
//									}
//								}
//								
//								//FATHER
//								if(i.getFathercifno() != null){
//									if(i.getFatherlastname()!=null && i.getFatherfirstname() !=null){
//										Tbcustomerrelationship f = new Tbcustomerrelationship();
//										String fmname = i.getFathermiddlename() == null ? "" :i.getFathermiddlename() == "" ? "" : " "+ i.getFathermiddlename();
//										String fsuffix = i.getFathersuffix() == null ? "" : i.getFathersuffix() == "" ? "" : " "+i.getFathersuffix();
//										String Fathername = i.getFatherlastname() + ", " + i.getFatherfirstname()+ fsuffix + fmname;
//										f.setAddedby(UserUtil.securityService.getUserName());
//										f.setDateadded(new Date());
//										f.setMaincifname(main.getFullname());
//										f.setMaincifno(main.getCifno());
//										f.setRelatedcifname(Fathername);
//										f.setRelatedcifno(i.getFathercifno());
//										f.setRelationshipcode("PAR");
//										params.put("relCode", f.getRelationshipcode());
//										Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//										if(rel != null){
//											f.setRelationshipdesc(rel.getDesc1());
//										}
//										f.setIsautogenerated(true);
//										if(dbService.save(f)){
//											f.setAddedby(UserUtil.securityService.getUserName());
//											f.setDateadded(new Date());
//											f.setMaincifname(Fathername);
//											f.setMaincifno(i.getFathercifno());
//											f.setRelatedcifname(main.getFullname());
//											f.setRelatedcifno(main.getCifno());
//											f.setRelationshipcode("CHI");
//											params.put("relCode", f.getRelationshipcode());
//											rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//											if(rel != null){
//												f.setRelationshipdesc(rel.getDesc1());
//											}
//											f.setIsautogenerated(true);
//											dbService.save(f);
//										}
//									}
//								}
//							}else{
//								StringBuilder s = new StringBuilder();
//								s.append("' '");
//								if(i.getMothercifno() != null){
//									s.append(",'"+i.getMothercifno()+"'");
//									if (i.getMotherlastname() != null && i.getMotherfirstname() != null) {
//										params.put("mCifno", i.getMothercifno());
//										Tbcustomerrelationship mother = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE maincifno=:cifno AND relatedcifno=:mCifno", params);
//										if(mother==null){
//											Tbcustomerrelationship m = new Tbcustomerrelationship();
//											String mmname = i.getMothermiddlename() == null ? "" :i.getMothermiddlename() == "" ? "" : " "+ i.getMothermiddlename();
//											String msuffix = i.getMothersuffix() == null ? "" : i.getMothersuffix() == "" ? "" : " " + i.getMothersuffix();
//											String mothername = i.getMotherlastname() + ", " + i.getMotherfirstname()+ msuffix + mmname;
//											m.setAddedby(UserUtil.securityService.getUserName());
//											m.setDateadded(new Date());
//											m.setMaincifname(main.getFullname());
//											m.setMaincifno(main.getCifno());
//											m.setRelatedcifname(mothername);
//											m.setRelatedcifno(i.getMothercifno());
//											m.setRelationshipcode("PAR");
//											params.put("relCode", m.getRelationshipcode());
//											Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//											if(rel != null){
//												m.setRelationshipdesc(rel.getDesc1());
//											}
//											m.setIsautogenerated(true);
//											if(dbService.save(m)){
//												m.setAddedby(UserUtil.securityService.getUserName());
//												m.setDateadded(new Date());
//												m.setMaincifname(mothername);
//												m.setMaincifno(i.getMothercifno());
//												m.setRelatedcifname(main.getFullname());
//												m.setRelatedcifno(main.getCifno());
//												m.setRelationshipcode("CHI");
//												params.put("relCode", m.getRelationshipcode());
//												rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//												if(rel != null){
//													m.setRelationshipdesc(rel.getDesc1());
//												}
//												m.setIsautogenerated(true);
//												dbService.save(m);
//											}
//										}else{
//											String mmname = i.getMothermiddlename() == null ? "" :i.getMothermiddlename() == "" ? "" : " "+ i.getMothermiddlename();
//											String msuffix = i.getMothersuffix() == null ? "" : i.getMothersuffix() == "" ? "" : " " + i.getMothersuffix();
//											String mothername = i.getMotherlastname() + ", " + i.getMotherfirstname()+ msuffix + mmname;
//											mother.setUpdatedby(UserUtil.securityService.getUserName());
//											mother.setDateupdated(new Date());
//											mother.setMaincifname(main.getFullname());
//											mother.setMaincifno(main.getCifno());
//											mother.setRelatedcifname(mothername);
//											mother.setRelatedcifno(i.getMothercifno());
//											mother.setRelationshipcode("PAR");
//											params.put("relCode", mother.getRelationshipcode());
//											Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//											if(rel != null){
//												mother.setRelationshipdesc(rel.getDesc1());
//											}
//											mother.setIsautogenerated(true);
//											if(dbService.saveOrUpdate(mother)){
//												Tbcustomerrelationship	child = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE maincifno=:mCifno AND relatedcifno=:cifno", params);
//												if(child != null){
//													child.setUpdatedby(UserUtil.securityService.getUserName());
//													child.setDateupdated(new Date());
//													child.setMaincifname(mothername);
//													child.setMaincifno(i.getMothercifno());
//													child.setRelatedcifname(main.getFullname());
//													child.setRelatedcifno(main.getCifno());
//													child.setRelationshipcode("CHI");
//													params.put("relCode", child.getRelationshipcode());
//													rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//													if(rel != null){
//														child.setRelationshipdesc(rel.getDesc1());
//													}
//													child.setIsautogenerated(true);
//													dbService.saveOrUpdate(child);
//												}
//											}
//										}
//									}
//								}
//								
//								if(i.getFathercifno()!=null){
//									s.append(",'"+i.getFathercifno()+"'");
//									if (i.getFatherlastname() != null && i.getFatherfirstname() != null) {
//										params.put("fCifno", i.getFathercifno());
//										Tbcustomerrelationship father = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE maincifno=:cifno AND relatedcifno=:fCifno", params);
//										if(father==null){
//											Tbcustomerrelationship f = new Tbcustomerrelationship();
//											String fmname = i.getFathermiddlename() == null ? "" :i.getFathermiddlename() == "" ? "" : " "+ i.getFathermiddlename();
//											String fsuffix = i.getFathersuffix() == null ? "" : i.getFathersuffix() == "" ? "" : " "+i.getFathersuffix();
//											String Fathername = i.getFatherlastname() + ", " + i.getFatherfirstname()+ fsuffix + fmname;
//											f.setAddedby(UserUtil.securityService.getUserName());
//											f.setDateadded(new Date());
//											f.setMaincifname(main.getFullname());
//											f.setMaincifno(main.getCifno());
//											f.setRelatedcifname(Fathername);
//											f.setRelatedcifno(i.getFathercifno());
//											f.setRelationshipcode("PAR");
//											params.put("relCode", f.getRelationshipcode());
//											Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//											if(rel != null){
//												f.setRelationshipdesc(rel.getDesc1());
//											}
//											f.setIsautogenerated(true);
//											if(dbService.save(f)){
//												f.setAddedby(UserUtil.securityService.getUserName());
//												f.setDateadded(new Date());
//												f.setMaincifname(Fathername);
//												f.setMaincifno(i.getFathercifno());
//												f.setRelatedcifname(main.getFullname());
//												f.setRelatedcifno(main.getCifno());
//												f.setRelationshipcode("CHI");
//												params.put("relCode", f.getRelationshipcode());
//												rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//												if(rel != null){
//													f.setRelationshipdesc(rel.getDesc1());
//												}
//												f.setIsautogenerated(true);
//												dbService.save(f);
//											}
//										}else{
//											String fmname = i.getFathermiddlename() == null ? "" :i.getFathermiddlename() == "" ? "" : " "+ i.getFathermiddlename();
//											String fsuffix = i.getFathersuffix() == null ? "" : i.getFathersuffix() == "" ? "" : " " + i.getFathersuffix();
//											String Fathername = i.getFatherlastname() + ", " + i.getFatherfirstname()+ fsuffix + fmname;
//											father.setUpdatedby(UserUtil.securityService.getUserName());
//											father.setDateupdated(new Date());
//											father.setMaincifname(main.getFullname());
//											father.setMaincifno(main.getCifno());
//											father.setRelatedcifname(Fathername);
//											father.setRelatedcifno(i.getFathercifno());
//											father.setRelationshipcode("PAR");
//											params.put("relCode", father.getRelationshipcode());
//											Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//											if(rel != null){
//												father.setRelationshipdesc(rel.getDesc1());
//											}
//											father.setIsautogenerated(true);
//											if(dbService.saveOrUpdate(father)){
//												Tbcustomerrelationship child = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE maincifno=:fCifno AND relatedcifno=:cifno", params);
//												if(child != null){
//													child.setUpdatedby(UserUtil.securityService.getUserName());
//													child.setDateupdated(new Date());
//													child.setMaincifname(Fathername);
//													child.setMaincifno(i.getFathercifno());
//													child.setRelatedcifname(main.getFullname());
//													child.setRelatedcifno(main.getCifno());
//													child.setRelationshipcode("CHI");
//													params.put("relCode", child.getRelationshipcode());
//													rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//													if(rel != null){
//														child.setRelationshipdesc(rel.getDesc1());
//													}
//													child.setIsautogenerated(true);
//													dbService.saveOrUpdate(child);
//												}
//											}
//										}
//									}
//								}
//								//delete parents
//								dbService.executeUpdate("DELETE FROM Tbcustomerrelationship WHERE relationshipcode ='PAR' AND maincifno IN (" + s.toString() + ") AND relatedcifno NOT IN(" + s.toString() + ")", null);
//
//								//delete child
//								dbService.executeUpdate("FROM Tbcustomerrelationship WHERE relationshipcode ='CHI' AND maincifno NOT IN (" + s.toString() + ") AND relatedcifno IN(" + s.toString() + ")", null);
//							}
//							
//							
//							/**----------EMPLOYMENT---------*/
//							List<Tbcifemployment> emp = (List<Tbcifemployment>) dbService.executeListHQLQuery("FROM Tbcifemployment WHERE cifno=:cifno AND positioncategory IS NOT NULL", params);
//							if(emp != null){
//								StringBuilder hqlEmp = new StringBuilder();
//								for(Tbcifemployment e : emp){
//									if(e.getEmpcifno() != null){
//										if(e.getEmployername()!=null){
//											hqlEmp.append(",'" + e.getEmpcifno() + "'");
//											params.put("empcifno", e.getEmpcifno());
//											List<Tbcifcorporate> corp = (List<Tbcifcorporate>) dbService.executeListHQLQuery("FROM Tbcifcorporate WHERE cifno=:empcifno", params);
//											if(corp != null){
//												String otherRel = e.getOtherpositioncategory();
//												String relCodeMain = "EMR";
//												String relCodeRel ="";
////												if(e.getPosition() != null && e.getPosition().equals("0")){
////													relCodeMain = "SHA";
////												}else if(e.getPosition() != null && e.getPosition().equals("1")){
////													relCodeMain = "DR";
////												}else if(e.getPosition() != null && (e.getPosition().equals("9") || e.getPosition().equals("10") ||e.getPosition().equals("11") ||e.getPosition().equals("12"))){
////													relCodeMain = "EMP";
////												}else{
////													relCodeMain = "OFF";
////												}
//												/*
//												 * Modified 09.28.2017 - Kevin 
//												 * */
//												if(e.getPositioncategory().equals("Stockholder/Shareholder")){
//													relCodeRel = "SHA";
//												}
//												if(e.getPositioncategory().equals("Director") || e.getPositioncategory().equals("Trustee")){
//													relCodeRel = "DR";
//												}
//												if(e.getPositioncategory().equals("Signatories")){
//													relCodeRel = "SIG";
//												}
//												if(e.getPositioncategory().equals("Junior Officer") || e.getPositioncategory().equals("Senior Officer")){
//													relCodeRel = "OFF";
//												}
//												if(e.getPositioncategory().equals("Others")){
//													relCodeRel = "EMP";
//												}
//												for (Tbcifcorporate c : corp) {
//													params.put("corpCifno", c.getCifno());
//													params.put("relCode", relCodeMain);
//													List<Tbcustomerrelationship> checker = (List<Tbcustomerrelationship>) dbService.executeListHQLQuery("FROM Tbcustomerrelationship WHERE maincifno=:cifno AND relatedcifno=:corpCifno AND relationshipcode=:relCode", params);
//													if(checker == null || checker.isEmpty()){
//														Tbcustomerrelationship r = new Tbcustomerrelationship();
//														String businessname = c.getCorporatename() == null ? "" : c.getCorporatename();
//														r.setAddedby(UserUtil.securityService.getUserName());
//														r.setDateadded(new Date());
//														r.setMaincifname(main.getFullname());
//														r.setMaincifno(main.getCifno());
//														r.setRelatedcifname(businessname);
//														r.setRelatedcifno(c.getCifno());
//														r.setRelationshipcode(relCodeMain);
//														params.put("relCode", r.getRelationshipcode());
//														Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//														if(rel != null){
//															r.setRelationshipdesc(rel.getDesc1());
//														}
//														r.setIsautogenerated(true);
//														if(dbService.save(r)){
//															Tbcustomerrelationship duplicateCheck = getCustRelationByRelCode(c.getCifno(),relCodeRel);
//															if(duplicateCheck == null){
//																r.setAddedby(UserUtil.securityService.getUserName());
//																r.setDateadded(new Date());
//																r.setMaincifname(businessname);
//																r.setMaincifno(c.getCifno());
//																r.setRelatedcifname(main.getFullname());
//																r.setRelatedcifno(main.getCifno());
//																r.setRelationshipcode(relCodeRel);
//																if(relCodeRel.equals("EMP")){
//																	r.setRelationshipdesc(otherRel);
//																}else{
//																	params.put("relCode", r.getRelationshipcode());
//																	rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//																	if(rel != null){
//																		r.setRelationshipdesc(rel.getDesc1());
//																	}
//																}
//																r.setIsautogenerated(true);
//																dbService.save(r);
//															}
//														}
//													}else{
//														int x=0;
//														while (x < checker.size()) {
//															x++;
//															Tbcustomerrelationship r = checker.get(x - 1);
//															String businessname = c.getCorporatename() == null ? "": c.getCorporatename();
//															r.setUpdatedby(UserUtil.securityService.getUserName());
//															r.setDateupdated(new Date());
//															r.setMaincifname(main.getFullname());
//															r.setMaincifno(main.getCifno());
//															r.setRelatedcifname(businessname);
//															r.setRelatedcifno(c.getCifno());
//															r.setRelationshipcode(relCodeMain);
//															params.put("relCode", r.getRelationshipcode());
//															Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//															if(rel != null){
//																r.setRelationshipdesc(rel.getDesc1());
//															}
//															r.setIsautogenerated(true);
//															if(dbService.saveOrUpdate(r)){
//																params.put("relcifno", r.getRelatedcifno());
//																Tbcustomerrelationship related = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE maincifno=:relcifno AND relatedcifno=:cifno", params);
//																if(related != null){
//																	Tbcustomerrelationship duplicateCheck = getCustRelationByRelCode(c.getCifno(),relCodeRel);
//																	if(duplicateCheck == null){
//																		related.setUpdatedby(UserUtil.securityService.getUserName());
//																		related.setDateupdated(new Date());
//																		related.setMaincifname(businessname);
//																		related.setMaincifno(c.getCifno());
//																		related.setRelatedcifname(main.getFullname());
//																		related.setRelatedcifno(main.getCifno());
//																		related.setRelationshipcode(relCodeRel);
//																		if(relCodeRel.equals("EMP")){
//																			related.setRelationshipdesc(otherRel);
//																		}else{
//																			params.put("relCode", related.getRelationshipcode());
//																			rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//																			if(rel != null){
//																				related.setRelationshipdesc(rel.getDesc1());
//																			}
//																		}
//																		related.setIsautogenerated(true);
//																		dbService.saveOrUpdate(related);
//																	}
//																}
//															}
//															
//														}
//													}
//												}//end of for loop tbcifcorporate
//											}
//										}
//									}
//								}
//								
//								//delete from Tbcustomerrelationship(EMPLOYMENT)
//								dbService.executeUpdate("DELETE FROM Tbcustomerrelationship WHERE maincifno=:cifno AND (relationshipcode IN('DR','OFF','SHA','EMP','SIG')) AND relatedcifno NOT IN(' '" + hqlEmp.toString() + ")", params);
//
//								//delete if not in TBEMPLOYMENT
//								List<Tbcustomerrelationship> custRel2 = (List<Tbcustomerrelationship>) dbService.executeListHQLQuery("FROM Tbcustomerrelationship WHERE maincifno=:cifno AND (relationshipcode IN('DR','OFF','SHA','EMP','SIG')) AND relatedcifno IN(' '" + hqlEmp.toString() + ")", params);
//								if(custRel2 != null){
//									for(Tbcustomerrelationship r2 : custRel2){
//										params.put("empcifno", r2.getRelatedcifno());
//										String position = "";
////										if(r2.getRelationshipcode().equals("SHA")){
////											position = "'0'";
////										}else if(r2.getRelationshipcode().equals("DR")){
////											position = "'1'";
////										}else if(r2.getRelationshipcode().equals("OFF")){
////											position = "'2','3','4','5','6','7','8'";
////										}else if(r2.getRelationshipcode().equals("EMP")){
////											position = "'9','10','11','12'";
////										}
//										
//										if(r2.getRelationshipcode().equals("SHA")){
//											position = "'Stockholder/Shareholder'";
//										}else if(r2.getRelationshipcode().equals("DR")){
//											position = "'Director','Trustee'";
//										}else if(r2.getRelationshipcode().equals("OFF")){
//											position = "'Junior Officer','Senior Officer'";
//										}else if(r2.getRelationshipcode().equals("SIG")){
//											position = "'Signatories'";
//										}else if(r2.getRelationshipcode().equals("EMP")){
//											position = "'Others'";
//										}
//										
//										Tbcifemployment cifEmp = (Tbcifemployment) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcifemployment WHERE cifno=:cifno AND empcifno=:empcifno AND positioncategory IN ("+position+")", params);
//										if(cifEmp == null){
//											if(r2.getRelationshipcode().equals("SHA")){
//												Integer mgtCount = (Integer) dbService.executeUniqueSQLQuery("SELECT COUNT(*) FROM Tbmanagement WHERE relatedcifno=:cifno AND cifno=:empcifno AND relationshipcode='SHA'", params);
//												if(mgtCount == 0){
//													dbService.delete(r2);
//												}
//											}else if(r2.getRelationshipcode().equals("SIG")){
//												Integer mgtCount = (Integer) dbService.executeUniqueSQLQuery("SELECT COUNT(*) FROM Tbmanagement WHERE relatedcifno=:cifno AND cifno=:empcifno AND relationshipcode='SIG'", params);
//												if(mgtCount == 0){
//													dbService.delete(r2);
//												}
//											}else{
//												dbService.delete(r2);
//											}
//										}
//									}
//								}
//								//delete from Tbcustomerrelationship(EMPLOYER)
//								dbService.executeUpdate("DELETE FROM Tbcustomerrelationship WHERE maincifno=:cifno AND relationshipcode ='EMR' AND relatedcifno NOT IN(' '" + hqlEmp.toString() + ")", params);
//								
////								dbService.executeUpdate("DELETE FROM Tbcustomerrelationship WHERE maincifno=:cifno AND relationshipcode ='EMR'", params);
////								
////								dbService.executeUpdate("DELETE FROM Tbcustomerrelationship WHERE relatedcifno=:cifno AND relationshipcode IN('DR','OFF','SHA','EMP','SIG')", params);
//								
//							
//							}else{
//								//delete from Tbcustomerrelationship(EMPLOYER)
//								dbService.executeUpdate("DELETE FROM Tbcustomerrelationship WHERE maincifno=:cifno AND relationshipcode ='EMR'", params);
//								
//								dbService.executeUpdate("DELETE FROM Tbcustomerrelationship WHERE relatedcifno=:cifno AND relationshipcode IN('DR','OFF','SHA','EMP','SIG')", params);
//								
//							}
//							
//							/*
//							 * 09 - Sole Proprietorship
//							 * 10 - General Partnership
//							 * 11 - Limited Partnership
//							 * 14 - Limited Partnership by Action
//							 * 16 - Limited liability company of unique partner
//							 * */
//							
//							/**----------BUSINESS---------**/
//							List<Tbcifbusiness> bus = (List<Tbcifbusiness>) dbService.executeListHQLQuery("FROM Tbcifbusiness WHERE cifno=:cifno AND businesstype IN ('9','09','10','11','14','16')", params);
//							if(bus != null){
//								StringBuilder hqlBus = new StringBuilder();
//								for(Tbcifbusiness b : bus){
//									if(b.getBuscifno() != null){
//										if(b.getBusinessname()!=null){
//											hqlBus.append(",'" + b.getBuscifno() + "'");
//											params.put("busCifno", b.getBuscifno());
//											List<Tbcifcorporate> corp = (List<Tbcifcorporate>) dbService.executeListHQLQuery("FROM Tbcifcorporate WHERE cifno=:busCifno", params);
//											if(corp != null){
//												String relCodeMain = "OWN";
//												String relCodeRel ="BUS";
//												for (Tbcifcorporate c : corp) {
//													params.put("corpCifno", c.getCifno());
//													params.put("relCode", relCodeMain);
//													List<Tbcustomerrelationship> checker = (List<Tbcustomerrelationship>) dbService.executeListHQLQuery("FROM Tbcustomerrelationship WHERE maincifno=:cifno AND relatedcifno=:corpCifno AND relationshipcode=:relCode", params);
//													if(checker == null || checker.isEmpty()){
//														Tbcustomerrelationship r = new Tbcustomerrelationship();
//														String businessname = c.getCorporatename() == null ? "" : c.getCorporatename();
//														r.setAddedby(UserUtil.securityService.getUserName());
//														r.setDateadded(new Date());
//														r.setMaincifname(main.getFullname());
//														r.setMaincifno(main.getCifno());
//														r.setRelatedcifname(businessname);
//														r.setRelatedcifno(c.getCifno());
//														r.setRelationshipcode(relCodeMain);
//														params.put("relCode", r.getRelationshipcode());
//														Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//														if(rel != null){
//															r.setRelationshipdesc(rel.getDesc1());
//														}
//														r.setIsautogenerated(true);
//														if(dbService.save(r)){
//															params.put("corpCifno", main.getCifno());
//															params.put("relCode", relCodeRel);
//															checker = (List<Tbcustomerrelationship>) dbService.executeListHQLQuery("FROM Tbcustomerrelationship WHERE maincifno=:corpCifno AND relatedcifno=:corpCifno AND relationshipcode=:relCode", params);
//															if(checker == null || checker.isEmpty()){
//																r = new Tbcustomerrelationship();
//																r.setAddedby(UserUtil.securityService.getUserName());
//																r.setDateadded(new Date());
//																r.setMaincifname(businessname);
//																r.setMaincifno(c.getCifno());
//																r.setRelatedcifname(main.getFullname());
//																r.setRelatedcifno(main.getCifno());
//																r.setRelationshipcode(relCodeRel);
//																params.put("relCode", r.getRelationshipcode());
//																rel = (Tbcodetable) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//																if(rel != null){
//																	r.setRelationshipdesc(rel.getDesc1());
//																}
//																r.setIsautogenerated(true);
//																 dbService.save(r);
//															}
//														}
//													}else{
//														int x=0;
//														while (x < checker.size()) {
//															x++;
//															Tbcustomerrelationship r = checker.get(x - 1);
//															String businessname = c.getCorporatename() == null ? "": c.getCorporatename();
//															r.setUpdatedby(UserUtil.securityService.getUserName());
//															r.setDateupdated(new Date());
//															r.setMaincifname(main.getFullname());
//															r.setMaincifno(main.getCifno());
//															r.setRelatedcifname(businessname);
//															r.setRelatedcifno(c.getCifno());
//															r.setRelationshipcode(relCodeMain);
//															params.put("relCode", r.getRelationshipcode());
//															Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//															if(rel != null){
//																r.setRelationshipdesc(rel.getDesc1());
//															}
//															r.setIsautogenerated(true);
//															if(dbService.saveOrUpdate(r)){
//																params.put("relcifno", r.getRelatedcifno());
//																Tbcustomerrelationship related = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE maincifno=:relcifno AND relatedcifno=:cifno", params);
//																if(related != null){
//																	related.setUpdatedby(UserUtil.securityService.getUserName());
//																	related.setDateupdated(new Date());
//																	related.setMaincifname(businessname);
//																	related.setMaincifno(c.getCifno());
//																	related.setRelatedcifname(main.getFullname());
//																	related.setRelatedcifno(main.getCifno());
//																	related.setRelationshipcode(relCodeRel);
//																	params.put("relCode", related.getRelationshipcode());
//																	rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//																	if(rel != null){
//																		related.setRelationshipdesc(rel.getDesc1());
//																	}
//																	related.setIsautogenerated(true);
//																	dbService.saveOrUpdate(related);
//																}
//															}
//														}
//													}
//												}//end of for loop tbcifcorporate
//											}
//										}
//									}
//								}
//								
//								//delete from Tbcustomerrelationship(BUSINESS)
//								dbService.executeUpdate("DELETE FROM Tbcustomerrelationship WHERE maincifno=:cifno AND relationshipcode ='OWN' AND relatedcifno NOT IN(''" + hqlBus.toString() + ")", params);
//								
//								//delete from Tbcustomerrelationship(BUSINESS 2)
//								dbService.executeUpdate("DELETE FROM Tbcustomerrelationship WHERE relatedcifno=:cifno AND relationshipcode ='BUS' AND maincifno NOT IN(''" + hqlBus.toString() + ")", params);
//							}
//						}
//					}else{
//						//Corporate
//						List<Tbmanagement> mgmt = (List<Tbmanagement>) dbService.executeListHQLQuery("FROM Tbmanagement WHERE cifno=:cifno",params);
//						if(mgmt == null || mgmt.isEmpty()){
//							//if Tbmanagement has no record.
//							Integer empCount = (Integer) dbService.executeUniqueSQLQuery("SELECT COUNT(*) FROM Tbcifemployment WHERE empcifno=:cifno", params);
//							Integer busCount = (Integer) dbService.executeUniqueSQLQuery("SELECT COUNT(*) FROM Tbcifbusiness WHERE buscifno=:cifno", params);
//							Integer mgtCount = (Integer) dbService.executeUniqueSQLQuery("SELECT COUNT(*) FROM Tbmanagement WHERE cifno=:cifno", params);
//							if(empCount == 0 && busCount == 0 && mgtCount == 0){
//								dbService.executeUpdate("DELETE FROM Tbcustomerrelationship WHERE maincifno=:cifno AND relationshipcode NOT IN('AFF','APE','SUB')", params);
//								dbService.executeUpdate("DELETE FROM Tbcustomerrelationship WHERE relatedcifno=:cifno AND relationshipcode NOT IN('AFF','APE','SUB')", params);
//							}
//						}else{
//							StringBuilder hqlRelCif = new StringBuilder();
//							List<String> relcode = new ArrayList<String>();
//							for(Tbmanagement m : mgmt){
//								relcode.add(m.getRelationshipcode());
//								String relCodeMain = "";
//								String relCodeRel ="";
//								if(m.getRelationshipcode() != null){
//									if(m.getRelationshipcode().equalsIgnoreCase("SHA")){
//										relCodeMain = m.getRelationshipcode();
//										relCodeRel ="EMR";
//										System.out.println("------------CORP SHA------------ " +relCodeRel );
//										System.out.println("------------Corp Sha relCodemain--------- " +relCodeMain);
//									}else if(m.getRelationshipcode().equalsIgnoreCase("P")){
//										relCodeMain = m.getRelationshipcode();
//										relCodeRel ="P";
//										System.out.println("------------CORP P ---------- " +relCodeRel);
//										System.out.println("------------Corp P relcodemain---------- "+relCodeMain);
//									}else if(m.getRelationshipcode().equalsIgnoreCase("SIG")){
//										relCodeMain = m.getRelationshipcode();
//										relCodeRel ="EMR";
//										System.out.println("-------------CORP SIG----------- " +relCodeRel);
//										System.out.println("-------------Corp Sig relcodemain--------- " +relCodeMain);
//									}else if(m.getRelationshipcode().equalsIgnoreCase("DR")){
//										relCodeMain = m.getRelationshipcode();
//										relCodeRel ="EMR";
//									}else if(m.getRelationshipcode().equalsIgnoreCase("OFF")){
//										relCodeMain = m.getRelationshipcode();
//										relCodeRel ="EMR";
//										System.out.println("---------- CORP OFF ------------ " +relCodeRel);
//										System.out.println("----------- Corp Off relcodemain ------------ " +relCodeMain);
//									}else if(m.getRelationshipcode().equalsIgnoreCase("OWN")){
//										relCodeMain = "BUS";
//										relCodeRel = m.getRelationshipcode();
//									}
//								}
//								hqlRelCif.append(",'" + m.getRelatedcifno() + "'");
//								params.put("relCifno", m.getRelatedcifno());
//								params.put("rCode", relCodeMain);
//								Tbcustomerrelationship manage = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE maincifno=:cifno AND relatedcifno=:relCifno AND relationshipcode=:rCode",params);
//								if(manage == null){
//									System.out.println("--------- PASS 1 --------------");
//									Tbcustomerrelationship c = new Tbcustomerrelationship();
//									String mname = m.getMiddlename() == null ? "" :m.getMiddlename() == "" ? "" : " "+ m.getMiddlename();
//									String suffix = m.getSuffix() == null ? "" : m.getSuffix() == "" ? "" : " " + m.getSuffix();
//									String name = "";
//									if(m.getCustomertype() != null && m.getCustomertype().equals("2")){
//										name = m.getCorporatename();
//									}else{
//										name = m.getLastname() + ", " + m.getFirstname()+ suffix + mname;
//									}
//									
//									c.setAddedby(UserUtil.securityService.getUserName());
//									c.setDateadded(new Date());
//									c.setMaincifname(main.getFullname());
//									c.setMaincifno(main.getCifno());
//									c.setRelatedcifname(name);
//									c.setRelatedcifno(m.getRelatedcifno());
//									c.setRelationshipcode(relCodeMain);
//									params.put("relCode", c.getRelationshipcode());
//									Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//									if(rel != null){
//										c.setRelationshipdesc(rel.getDesc1());
//									}
//									c.setIsautogenerated(true);
//									if(dbService.save(c)){
//										System.out.println("---------- PASS 2 --------------");
//										params.put("relCodeRel", relCodeRel);
//										System.out.println("----------PASS 2 relcodeRel----------" +relCodeRel);
//										Tbcustomerrelationship checker = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE maincifno=:relCifno AND relatedcifno=:cifno AND relationshipcode=:relCodeRel", params);
//										if(checker == null){
//											System.out.println("------- PASS 4 ------------");
//											c.setAddedby(UserUtil.securityService.getUserName());
//											c.setDateadded(new Date());
//											c.setMaincifname(name);
//											c.setMaincifno(m.getRelatedcifno());
//											c.setRelatedcifname(main.getFullname());
//											c.setRelatedcifno(main.getCifno());
//											c.setRelationshipcode(relCodeRel);
//											params.put("relCode", c.getRelationshipcode());
//											rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//											if(rel != null){
//												c.setRelationshipdesc(rel.getDesc1());
//											}
//											c.setIsautogenerated(true);
//											if(relCodeRel != null && relCodeRel != ""){
//												dbService.save(c);
//												System.out.println("--------PASS 3 ------------");
//											}
//										}
//									}
//								}else{
//									String mname = m.getMiddlename() == null ? "" :m.getMiddlename() == "" ? "" : " "+ m.getMiddlename();
//									String suffix = m.getSuffix() == null ? "" : m.getSuffix() == "" ? "" : " " + m.getSuffix();
//									String name = "";
//									if(m.getCustomertype() != null && m.getCustomertype().equals("2")){
//										name = m.getCorporatename();
//									}else{
//										name = m.getLastname() + ", " + m.getFirstname()+ suffix + mname;
//									}
//									manage.setUpdatedby(UserUtil.securityService.getUserName());
//									manage.setDateupdated(new Date());
//									manage.setMaincifname(main.getFullname());
//									manage.setMaincifno(main.getCifno());
//									manage.setRelatedcifname(name);
//									manage.setRelatedcifno(m.getRelatedcifno());
//									manage.setRelationshipcode(relCodeMain);
//									params.put("relCode", manage.getRelationshipcode());
//									Tbcodetable rel = (Tbcodetable) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//									if(rel != null){
//										manage.setRelationshipdesc(rel.getDesc1());
//									}
//									manage.setIsautogenerated(true);
//									if(dbService.saveOrUpdate(manage)){
//										System.out.println(" ---------- PASS 5 ----------- ");
//										params.put("relcifno", manage.getRelatedcifno());
//										System.out.println("----- PASS 5 relcifno ------- " + manage.getRelatedcifno());
//										params.put("relCodeRel", relCodeRel);
//										System.out.println("------ PASS 5 relcoderel ---------- " +relCodeRel);
//										
//										Tbcustomerrelationship related = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE maincifno=:relcifno AND relatedcifno=:cifno AND relationshipcode=:relCodeRel", params);
//										if(related != null){
//											System.out.println(" --------- PASS 6 ------------ ");
//											related.setUpdatedby(UserUtil.securityService.getUserName());
//											related.setDateupdated(new Date());
//											related.setMaincifname(name);
//											related.setMaincifno(m.getRelatedcifno());
//											related.setRelatedcifname(main.getFullname());
//											related.setRelatedcifno(main.getCifno());
//											related.setRelationshipcode(relCodeRel);
//											params.put("relCode", related.getRelationshipcode());
//											rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//											if(rel != null){
//												related.setRelationshipdesc(rel.getDesc1());
//											}
//											related.setIsautogenerated(true);
//											if(relCodeRel != null && relCodeRel != ""){
//												dbService.saveOrUpdate(related);
//												System.out.println(" --------- PASS 7 ---------- ");
//											}
//										}else{
//											System.out.println(" -------- PASS 8 -------- ");
//											related = new Tbcustomerrelationship();
//											related.setAddedby(UserUtil.securityService.getUserName());
//											related.setDateadded(new Date());
//											related.setMaincifname(name);
//											related.setMaincifno(m.getRelatedcifno());
//											related.setRelatedcifname(main.getFullname());
//											related.setRelatedcifno(main.getCifno());
//											related.setRelationshipcode(relCodeRel);
//											params.put("relCode", related.getRelationshipcode());
//											rel = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//											if(rel != null){
//												related.setRelationshipdesc(rel.getDesc1());
//											}
//											related.setIsautogenerated(true);
//											if(relCodeRel != null && relCodeRel != ""){
//												dbService.saveOrUpdate(related);
//												System.out.println("---------- PASS 9 ---------");
//											}
//										}
//									}
//								}
//							}
//							
//							//delete 
//							dbService.executeUpdate("DELETE FROM Tbcustomerrelationship WHERE maincifno=:cifno AND (relationshipcode IN('SHA','P','SIG','DR','OWN','OFF')) AND relatedcifno NOT IN(' '" + hqlRelCif.toString() + ")", params);
//							//System.out.println("d1: FROM Tbcustomerrelationship WHERE maincifno=:cifno AND (relationshipcode IN('SHA','P','SIG','DR','OWN','OFF')) AND relatedcifno NOT IN(' '" + hqlRelCif.toString() + ")");
//							//delete if not in tbmanagement
//							dbService.executeListSQLQuery("with cte as(select relid,maincifno,maincifname,relatedcifno,relationshipcode,"
//									+ "relatedcifname,status,dateadded,addedby,dateupdated,updatedby,isautogenerated,relationshipdesc,"
//									+ " RN =  ROW_NUMBER() over (Partition by relatedcifno,relationshipcode order by relatedcifno) "
//									+ "from TBCUSTOMERRELATIONSHIP)delete from cte where RN > 1 and maincifno =:cifno", params);
//							List<Tbcustomerrelationship> delSig = (List<Tbcustomerrelationship>) dbService.executeListHQLQuery("FROM Tbcustomerrelationship WHERE maincifno=:cifno AND relationshipcode IN('SHA','P','SIG','DR','OWN','OFF')", params);
//							//System.out.println("d2: FROM Tbcustomerrelationship WHERE maincifno=:cifno AND relationshipcode IN('SHA','P','SIG','DR','OWN','OFF')");
//							if(delSig != null){
//								for(Tbcustomerrelationship s : delSig){
//									params.put("mgtRelcif", s.getRelatedcifno());
//									params.put("mgtRelcode", s.getRelationshipcode());
//									Tbmanagement sig = (Tbmanagement) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbmanagement WHERE cifno=:cifno AND relatedcifno=:mgtRelcif  AND relationshipcode=:mgtRelcode",params);
//									if(sig == null){
//										dbService.delete(s);
//									}
//								}
//							}
//							
//							//delete 
//							dbService.executeUpdate("DELETE FROM Tbcustomerrelationship WHERE relatedcifno=:cifno AND (relationshipcode IN('SHA','P','EMR','BUS')) AND maincifno NOT IN(' '" + hqlRelCif.toString() + ")", params);
//							//System.out.println("d3: FROM Tbcustomerrelationship WHERE relatedcifno=:cifno AND (relationshipcode IN('SHA','P','EMR','BUS')) AND maincifno NOT IN(' '" + hqlRelCif.toString() + ")");
//							
//							//delete if not in tbmanagement
//							List<Tbcustomerrelationship> delMgt3 = (List<Tbcustomerrelationship>) dbService.executeListHQLQuery("FROM Tbcustomerrelationship WHERE relatedcifno=:cifno AND (relationshipcode IN('SHA','P','EMR','BUS'))", params);
//							//System.out.println("d4: FROM Tbcustomerrelationship WHERE relatedcifno=:cifno AND (relationshipcode IN('SHA','P','EMR','BUS'))");
//							if(delMgt3 != null){
//								for(Tbcustomerrelationship p : delMgt3){
//									params.put("mgtRelcif", p.getMaincifno());
//									params.put("mgtRelcode", p.getRelationshipcode());
//									String hql ="  AND relationshipcode=:mgtRelcode";
//									if(p.getRelationshipcode().equals("EMR")){
//										hql ="  AND relationshipcode IN ('OFF','DR')";
//									}else if(p.getRelationshipcode().equals("BUS")){
//										hql ="  AND relationshipcode='OWN'";
//									}
//									Tbmanagement mgt3 = (Tbmanagement) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbmanagement WHERE cifno=:cifno AND relatedcifno=:mgtRelcif" + hql ,params);
//									Tbmanagement mgt4 = (Tbmanagement) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbmanagement WHERE cifno=:mgtRelcif AND relatedcifno=:cifno" + hql ,params);
//									if(mgt3 == null && mgt4 == null){
//										dbService.delete(p);
//									}
//									
//								}
//							}
//							
//						}
//					}
//				}
//			}
//			flag="success";
//			//update name
//			updateRelationshipNames(cifno);
//		} catch (Exception e) {
//			e.printStackTrace();
//		}
//		return flag;
//	}
	
	@SuppressWarnings("unchecked")
	@Override
	public List<Relationshipform> getListOfCustRelationShip(String cifno, Boolean isconcatenated) {
		DBService dbService = new DBServiceImplCIF();
		Map<String, Object> params = HQLUtil.getMap();
		List<Relationshipform>  relation = new ArrayList<Relationshipform>();
		try {
			if (cifno != null) {
				params.put("maincifno", cifno);
				
				if(isconcatenated != null && isconcatenated){
					relation = (List<Relationshipform>) dbService.execStoredProc(
							"SELECT DISTINCT a.relatedcifno, a.relatedcifname, CONVERT(varchar(100),(STUFF((SELECT DISTINCT ', ' + b.relationshipdesc FROM TBCUSTOMERRELATIONSHIP b WHERE b.relatedcifno = a.relatedcifno AND b.maincifno = a.maincifno  FOR XML PATH('')), 1, 2, ''))) as relationshipcode FROM TBCUSTOMERRELATIONSHIP a WHERE a.maincifno=:maincifno",
							params, Relationshipform.class, 1, null);
				} else {
					relation = (List<Relationshipform>) dbService.execStoredProc(
							"SELECT a.relatedcifno, a.relatedcifname, a.relationshipdesc as relationshipcode, a.isautogenerated, relid FROM TBCUSTOMERRELATIONSHIP a WHERE a.maincifno =:maincifno",
							params, Relationshipform.class, 1, null);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return relation;
	}
	
	@SuppressWarnings("unchecked")
	public static List<Tbcustomerrelationship> getListOfCustRelationByRelCode(String maincifno, String relationshipcode) {
		DBService dbService = new DBServiceImplCIF();
		Map<String, Object> params = HQLUtil.getMap();
		List<Tbcustomerrelationship>  relation = new ArrayList<Tbcustomerrelationship>();
		try {
			if (maincifno != null) {
				params.put("maincifno", maincifno);
				params.put("relationshipcode", relationshipcode);
				relation = (List<Tbcustomerrelationship>) dbService.executeListHQLQuery("FROM Tbcustomerrelationship WHERE maincifno=:maincifno AND relationshipcode=:relationshipcode", params);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return relation;
	}
	
	public static Tbcustomerrelationship getCustRelationByRelCode(String maincifno, String relationshipcode) {
		DBService dbService = new DBServiceImplCIF();
		Map<String, Object> params = HQLUtil.getMap();
		Tbcustomerrelationship relation = new Tbcustomerrelationship();
		try {
			if (maincifno != null) {
				params.put("maincifno", maincifno);
				params.put("relationshipcode", relationshipcode);
				relation = (Tbcustomerrelationship) dbService.executeUniqueHQLQuery("FROM Tbcustomerrelationship WHERE maincifno=:maincifno AND relationshipcode=:relationshipcode",params);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return relation;
	}

	@Override
	public FormValidation addRelationship(Tbcustomerrelationship rel, String addOrUpdateFlag) {
		FormValidation form = new FormValidation();
		form.setFlag("failed");
		DBService dbService = new DBServiceImplCIF();
		Map<String, Object> params = HQLUtil.getMap();
		params.put("maincifno", rel.getMaincifno());
		params.put("relatedcifno", rel.getRelatedcifno());
		params.put("relationshipcode", rel.getRelationshipcode());
		Tbcustomerrelationship relation =null;
		try {
			
			// Sept.10.2018
			if(rel.getMaincifno()!=null && rel.getRelatedcifno()!=null && (rel.getRelationshipcode()!=null && rel.getRelationshipcode().equals("SUB"))){
				String row = (String) dbService.executeUniqueSQLQuery
						("SELECT TOP 1 maincifno FROM Tbcustomerrelationship WHERE maincifno<>:maincifno AND relatedcifno=:relatedcifno AND relationshipcode='SUB'", params);
				if(row!=null){
					String row2 = (String) dbService.executeUniqueSQLQuery
							("SELECT TOP 1 maincifname FROM Tbcustomerrelationship WHERE maincifno<>:maincifno AND relatedcifno=:relatedcifno AND relationshipcode='SUB'", params);
					form.setErrorMessage("<b>FAILED! </b>CIF already used as subsidiary of <b> [ " + row +","+ row2 + " ]</b>.");
					return form;
				}
			}
			
			String maincifname="";
			Tbcifmain main = (Tbcifmain) dbService.executeUniqueHQLQuery("FROM Tbcifmain WHERE cifno=:maincifno", params);
			relation = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne
					("FROM Tbcustomerrelationship WHERE maincifno=:maincifno AND relatedcifno=:relatedcifno AND relationshipcode=:relationshipcode", params);
			
			if(main !=null){
				maincifname = main.getFullname();
			}
			if(addOrUpdateFlag != null && addOrUpdateFlag.equalsIgnoreCase("add")){
				if(relation != null){
					form.setErrorMessage("<b>FAILED! </b>Relationship already exists.");
					return form;
				}else{
					relation = new Tbcustomerrelationship();
					relation.setMaincifno(rel.getMaincifno());
					relation.setMaincifname(maincifname);
					relation.setRelatedcifname(rel.getRelatedcifname());
					relation.setRelatedcifno(rel.getRelatedcifno());
					relation.setRelationshipcode(rel.getRelationshipcode());
					params.put("relCode", relation.getRelationshipcode());
					Tbcodetable relcode = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
					if(rel != null){
						relation.setRelationshipdesc(relcode.getDesc1());
					}
					relation.setDateadded(new Date());
					relation.setAddedby(UserUtil.securityService.getUserName());
					relation.setIsautogenerated(false);
					if(dbService.save(relation)){
						if(rel.getRelationshipcode().equalsIgnoreCase("AFF") || rel.getRelationshipcode().equalsIgnoreCase("SUB")){
							params.put("relationshipcode", "APE");
							params.put("maincifno", rel.getRelatedcifno());
							params.put("relatedcifno", rel.getMaincifno());
							relation = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE maincifno=:maincifno AND relatedcifno=:relatedcifno AND relationshipcode=:relationshipcode", params);
							if(relation != null){
								//There's an existing data.
							}else{
								relation = new Tbcustomerrelationship();
								relation.setRelatedcifname(maincifname);
								relation.setRelatedcifno(rel.getMaincifno());
								relation.setMaincifname(rel.getRelatedcifname());
								relation.setMaincifno(rel.getRelatedcifno());
								relation.setRelationshipcode("APE");
								params.put("relCode", relation.getRelationshipcode());
								relcode = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
								if(rel != null){
									relation.setRelationshipdesc(relcode.getDesc1());
								}
								relation.setDateadded(new Date());
								relation.setAddedby(UserUtil.securityService.getUserName());
								relation.setIsautogenerated(true);
								dbService.save(relation);
							}
						}else if(rel.getRelationshipcode().equalsIgnoreCase("APE")){ // September 1, 2018
							params.put("relationshipcode", "SUB");
							params.put("maincifno", rel.getRelatedcifno());
							params.put("relatedcifno", rel.getMaincifno());
							relation = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE maincifno=:maincifno AND relatedcifno=:relatedcifno AND relationshipcode=:relationshipcode", params);
							if(relation != null){
								//There's an existing data.
							}else{
								relation = new Tbcustomerrelationship();
								relation.setRelatedcifname(maincifname);
								relation.setRelatedcifno(rel.getMaincifno());
								relation.setMaincifname(rel.getRelatedcifname());
								relation.setMaincifno(rel.getRelatedcifno());
								relation.setRelationshipcode("SUB");
								params.put("relCode", relation.getRelationshipcode());
								relcode = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
								if(rel != null){
									relation.setRelationshipdesc(relcode.getDesc1());
								}
								relation.setDateadded(new Date());
								relation.setAddedby(UserUtil.securityService.getUserName());
								relation.setIsautogenerated(true);
								dbService.save(relation);
							}						
						}
						form.setFlag("success");
					}
				}
			}else {
				params.put("id", rel.getRelid());
				relation = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE maincifno=:maincifno AND relid=:id", params);
				if(relation != null){
					if(relation.getIsautogenerated() != null && relation.getIsautogenerated()){
						form.setErrorMessage("<b>FAILED! </b>System-generated info cannot update.");
						return form;
					}else{
						relation.setRelatedcifno(rel.getRelatedcifno());
						relation.setRelatedcifname(rel.getRelatedcifname());
						relation.setRelationshipcode(rel.getRelationshipcode());
						params.put("relCode", relation.getRelationshipcode());
						Tbcodetable relcode = (Tbcodetable) dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
						if(rel != null){
							relation.setRelationshipdesc(relcode.getDesc1());
						}
						relation.setDateupdated(new Date());
						relation.setUpdatedby(UserUtil.securityService.getUserName());
						if (dbService.saveOrUpdate(relation)) {
							form.setFlag("success");
						}
					}
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return form;
	}

	@Override
	public FormValidation deleteRelationship(Integer id) {
		FormValidation form = new FormValidation();
		form.setFlag("failed");
		DBService dbService = new DBServiceImplCIF();
		Map<String, Object> params = HQLUtil.getMap();
		params.put("id", id);
		try {
			Tbcustomerrelationship rel = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE relid=:id", params);
			if(rel != null){
				if(rel.getIsautogenerated() != null && rel.getIsautogenerated()){
					form.setErrorMessage("<b>FAILED! </b>System-generated info cannot delete.");
					return form;
				}else{
					if(dbService.delete(rel)){
						form.setFlag("success");
						params.put("maincifno", rel.getMaincifno());
						params.put("relcifno", rel.getRelatedcifno());
						rel = (Tbcustomerrelationship) dbService.executeUniqueHQLQueryMaxResultOne("FROM Tbcustomerrelationship WHERE maincifno=:relcifno AND relatedcifno=:maincifno AND relationshipcode='APE'", params);
						if(rel != null){
							dbService.delete(rel);
						}
					}
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return form;
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<CodetableForm> getRelationshipCode() {
		List<CodetableForm> codelist = new ArrayList<CodetableForm>();
		DBService dbService = new DBServiceImplCIF();
		try {
			List<Tbcodetable> codetable = (List<Tbcodetable>) dbService.executeListHQLQuery("FROM Tbcodetable a WHERE a.id.codename='RELATIONSHIPCODE' AND a.id.codevalue IN ('AFF','SUB','APE')", null);
			if (codetable != null) {
				for (Tbcodetable ct : codetable) {
					CodetableForm form = new CodetableForm();
					form.setCodename(ct.getId().getCodename());
					form.setCodevalue(ct.getId().getCodevalue());
					form.setDesc1(ct.getDesc1());
					form.setDesc2(ct.getDesc2());
					form.setRemarks(ct.getRemarks());
					codelist.add(form);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return codelist;
	}
	
	public String updateRelationshipNames(String cifno){
		String flag="failed";
		DBService dbService = new DBServiceImplCIF();
		try {
			if(cifno != null){
				dbService.executeUpdate("UPDATE Tbcustomerrelationship SET maincifname=(SELECT fullname FROM TBCIFMAIN WHERE cifno='"+cifno+"') WHERE maincifno='"+cifno+"'", null);
				dbService.executeUpdate("UPDATE Tbcustomerrelationship SET relatedcifname=(SELECT fullname FROM TBCIFMAIN WHERE cifno='"+cifno+"') WHERE relatedcifno='"+cifno+"'", null);
			}
			flag="success";
		} catch (Exception e) {
			flag="failed";
			e.printStackTrace();
		}
		return flag;
	}
	//JAY 12-6-18
	//no dedupe
	
//	@Override
//	public String AddCustTraderef(String cifno,String tradecifno, String tradetype) {
//		// TODO Auto-generated method stub
//		DBService dbService = new DBServiceImplCIF();
//		String flag = "failed";
//		Map<String,Object> params = HQLUtil.getMap();
//		
//		try {
//			if(cifno !=  null){
//				params.put("cifno",cifno);
//				params.put("tradecifno", tradecifno);
//				params.put("tradetype", tradetype);
//				System.out.println("custrel cifno: " +cifno+ " custrel tradecifno: " +tradecifno+ "custrel tradetype: " +tradetype);
//				System.out.println("------- CUSTREL TRADE REF cifno -------- " +cifno);
//				Tbtradereference tr = (Tbtradereference) dbService.executeUniqueHQLQuery(
//						"FROM Tbtradereference WHERE cifno=:cifno AND tradecifno=:tradecifno AND tradetype=:tradetype",
//						params);
//
//				params.put("maincifno", tr.getId().getCifno());
//				Tbcifmain main = (Tbcifmain)dbService.executeUniqueHQLQuery("FROM Tbcifmain WHERE cifno=:maincifno", params);
//				if(tr != null){
//					/** ------ ADD CLIENT(Indiv/Corp) ---------- */
//					if(tr.getId().getTradetype().equals("0")){
//									Tbcustomerrelationship cust = new Tbcustomerrelationship();
//									cust.setMaincifno(main.getCifno());
//									cust.setMaincifname(main.getFullname());
//									cust.setRelatedcifno(tr.getId().getTradecifno());
//									cust.setRelationshipcode("CLN");
//									cust.setRelatedcifname(tr.getClientsuppliername());
//									cust.setDateadded(new Date());
//									cust.setMngempid(main.getCifno());
//									cust.setAddedby(UserUtil.securityService.getUserName());
//									params.put("relCode", cust.getRelationshipcode());
//									Tbcodetable rel = (Tbcodetable)dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//									if(rel != null){
//										cust.setRelationshipdesc(rel.getDesc1());
//									}
//									cust.setIsautogenerated(true);
//									if(dbService.save(cust)){
//										System.out.println("Added Client Relationship CIFNO : "+cust.getRelatedcifno());
//										cust.setAddedby(UserUtil.securityService.getUserName());
//										cust.setDateadded(new Date());
//										cust.setMaincifname(tr.getClientsuppliername());
//										cust.setMaincifno(tr.getId().getTradecifno());
//										cust.setRelatedcifno(tr.getId().getCifno());
//										cust.setRelatedcifname(main.getFullname());
//										cust.setRelationshipcode("SUP");
//										cust.setMngempid(main.getCifno());
//										params.put("relCode", cust.getRelationshipcode());
//										rel = (Tbcodetable)dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' and id.codevalue=:relCode", params);
//										if(rel != null){
//											cust.setRelationshipdesc(rel.getDesc1());
//										}
//										dbService.save(cust);
//										flag = "Success";
//										System.out.println("Added Supplier Relationship CIFNO: "+cust.getMaincifno());
//									}
//								}
//						/** -------- ADD SUPPLIER (Indiv/Corp) ---------- */
//						else{
//									Tbcustomerrelationship cust = new Tbcustomerrelationship();
//									cust.setMaincifno(main.getCifno());
//									cust.setMaincifname(main.getFullname());
//									cust.setRelatedcifno(tr.getId().getTradecifno());
//									cust.setRelationshipcode("SUP");
//									cust.setRelatedcifname(tr.getClientsuppliername());
//									cust.setDateadded(new Date());
//									cust.setMngempid(main.getCifno());
//									cust.setAddedby(UserUtil.securityService.getUserName());
//									params.put("relCode", cust.getRelationshipcode());
//									Tbcodetable rel = (Tbcodetable)dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
//									if(rel != null){
//										cust.setRelationshipdesc(rel.getDesc1());
//									}
//									cust.setIsautogenerated(true);
//									if(dbService.save(cust)){
//										System.out.println("Added Supplier Relationship CIFNO: " +cust.getMaincifno());
//										cust.setAddedby(UserUtil.securityService.getUserName());
//										cust.setDateadded(new Date());
//										cust.setMaincifname(tr.getClientsuppliername());
//										cust.setMaincifno(tr.getId().getTradecifno());
//										cust.setRelatedcifno(tr.getId().getCifno());
//										cust.setRelatedcifname(main.getFullname());
//										cust.setRelationshipcode("CLN");
//										cust.setMngempid(main.getCifno());
//										params.put("relCode", cust.getRelationshipcode());
//										rel = (Tbcodetable)dbService.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' and id.codevalue=:relCode", params);
//										if(rel != null){
//											cust.setRelationshipdesc(rel.getDesc1());
//										}
//										dbService.save(cust);
//										flag = "Success";
//										System.out.println("Added Client Relationship CIFNO: " +cust.getMaincifno());
//									}
//									
//								}
//								
//								
//							}
//				}
//			
//		} catch (Exception e) {
//			// TODO: handle exception
//			e.printStackTrace();
//		}
//		return flag;
//	}
	
	//MAR 10-23-2020
	@Override
	public String AddCustTraderefRB(String cifno,String tradecifno, String tradetype) {
		// TODO Auto-generated method stub
		DBService dbServiceCOOP = new DBServiceImpl();
		String flag = "failed";
		Map<String,Object> params = HQLUtil.getMap();
		
		try {
			if(cifno !=  null){
				params.put("cifno",cifno);
				params.put("tradecifno", tradecifno);
				params.put("tradetype", tradetype);
				System.out.println("custrel cifno: " +cifno+ " custrel tradecifno: " +tradecifno+ "custrel tradetype: " +tradetype);
				System.out.println("------- CUSTREL TRADE REF cifno -------- " +cifno);
				Tbtradereferencelos tr = (Tbtradereferencelos) dbServiceCOOP.executeUniqueHQLQuery(
						"FROM Tbtradereferencelos WHERE cifno=:cifno AND tradecifno=:tradecifno AND tradetype=:tradetype",
						params);

				params.put("maincifno", tr.getId().getCifno());
				Tblosmain main = (Tblosmain)dbServiceCOOP.executeUniqueHQLQuery("FROM Tblosmain WHERE cifno=:maincifno", params);
				if(tr != null){
					/** ------ ADD CLIENT(Indiv/Corp) ---------- */
					if(tr.getId().getTradetype().equals("0")){
									Tbcustomerrelationshiplos cust = new Tbcustomerrelationshiplos();
									cust.setMaincifno(main.getCifno());
									cust.setMaincifname(main.getFullname());
									cust.setRelatedcifno(tr.getId().getTradecifno());
									cust.setRelationshipcode("CLN");
									cust.setRelatedcifname(tr.getClientsuppliername());
									cust.setDateadded(new Date());
									cust.setMngempid(main.getCifno());
									cust.setAddedby(UserUtil.securityService.getUserName());
									params.put("relCode", cust.getRelationshipcode());
									Tbcodetable rel = (Tbcodetable)dbServiceCOOP.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
									if(rel != null){
										cust.setRelationshipdesc(rel.getDesc1());
									}
									cust.setIsautogenerated(true);
									if(dbServiceCOOP.save(cust)){
										System.out.println("Added Client Relationship CIFNO : "+cust.getRelatedcifno());
										cust.setAddedby(UserUtil.securityService.getUserName());
										cust.setDateadded(new Date());
										cust.setMaincifname(tr.getClientsuppliername());
										cust.setMaincifno(tr.getId().getTradecifno());
										cust.setRelatedcifno(tr.getId().getCifno());
										cust.setRelatedcifname(main.getFullname());
										cust.setRelationshipcode("SUP");
										cust.setMngempid(main.getCifno());
										params.put("relCode", cust.getRelationshipcode());
										rel = (Tbcodetable)dbServiceCOOP.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' and id.codevalue=:relCode", params);
										if(rel != null){
											cust.setRelationshipdesc(rel.getDesc1());
										}
										dbServiceCOOP.save(cust);
										flag = "Success";
										System.out.println("Added Supplier Relationship CIFNO: "+cust.getMaincifno());
									}
								}
						/** -------- ADD SUPPLIER (Indiv/Corp) ---------- */
						else{
									Tbcustomerrelationshiplos cust = new Tbcustomerrelationshiplos();
									cust.setMaincifno(main.getCifno());
									cust.setMaincifname(main.getFullname());
									cust.setRelatedcifno(tr.getId().getTradecifno());
									cust.setRelationshipcode("SUP");
									cust.setRelatedcifname(tr.getClientsuppliername());
									cust.setDateadded(new Date());
									cust.setMngempid(main.getCifno());
									cust.setAddedby(UserUtil.securityService.getUserName());
									params.put("relCode", cust.getRelationshipcode());
									Tbcodetable rel = (Tbcodetable)dbServiceCOOP.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' AND id.codevalue=:relCode", params);
									if(rel != null){
										cust.setRelationshipdesc(rel.getDesc1());
									}
									cust.setIsautogenerated(true);
									if(dbServiceCOOP.save(cust)){
										System.out.println("Added Supplier Relationship CIFNO: " +cust.getMaincifno());
										cust.setAddedby(UserUtil.securityService.getUserName());
										cust.setDateadded(new Date());
										cust.setMaincifname(tr.getClientsuppliername());
										cust.setMaincifno(tr.getId().getTradecifno());
										cust.setRelatedcifno(tr.getId().getCifno());
										cust.setRelatedcifname(main.getFullname());
										cust.setRelationshipcode("CLN");
										cust.setMngempid(main.getCifno());
										params.put("relCode", cust.getRelationshipcode());
										rel = (Tbcodetable)dbServiceCOOP.executeUniqueHQLQuery("FROM Tbcodetable WHERE id.codename='RELATIONSHIPCODE' and id.codevalue=:relCode", params);
										if(rel != null){
											cust.setRelationshipdesc(rel.getDesc1());
										}
										dbServiceCOOP.save(cust);
										flag = "Success";
										System.out.println("Added Client Relationship CIFNO: " +cust.getMaincifno());
									}
									
								}
								
								
							}
				}
			
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		return flag;
	}

	@SuppressWarnings("unchecked")
	public List<Relationshipform> getListOfCustRelationShipRB(String cifno, Boolean isconcatenated) {
		DBService dbServiceCOOP = new DBServiceImpl();
		Map<String, Object> params = HQLUtil.getMap();
		List<Relationshipform>  relation = new ArrayList<Relationshipform>();
		try {
			if (cifno != null) {
				params.put("maincifno", cifno);
				
				if(isconcatenated != null && isconcatenated){
					relation = (List<Relationshipform>) dbServiceCOOP.execStoredProc(
							"SELECT DISTINCT a.relatedcifno, a.relatedcifname, CONVERT(varchar(100),(STUFF((SELECT DISTINCT ', ' + b.relationshipdesc FROM TBCUSTOMERRELATIONSHIPLOS b WHERE b.relatedcifno = a.relatedcifno AND b.maincifno = a.maincifno  FOR XML PATH('')), 1, 2, ''))) as relationshipcode FROM TBCUSTOMERRELATIONSHIPLOS a WHERE a.maincifno=:maincifno",
							params, Relationshipform.class, 1, null);
				} else {
					relation = (List<Relationshipform>) dbServiceCOOP.execStoredProc(
							"SELECT a.relatedcifno, a.relatedcifname, a.relationshipdesc as relationshipcode, a.isautogenerated, relid FROM TBCUSTOMERRELATIONSHIPLOS a WHERE a.maincifno =:maincifno",
							params, Relationshipform.class, 1, null);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return relation;
	}
	
	
}
